// This file contains all internship opportunities.
// To add a new one, just add a new object to this array.

export const internships = [
    {
        id: "aicte_1",
        type: "internship",
        title: "WEB DEVELOPMENT",
        company: "Horizon Flare India",
        source: "AICTE",
        location: "Virtual",
        amount: 1000,
        applyBy: "2025-11-30",
        skills: "React, Node.js, MongoDB, Express",
        url: "https://internship.aicte-india.org/internship-details.php?uid=SU5URVJOU0hJUF8xNzYyMDAxNDgyNjkwNjAyNGE5YTQwMg=="
    },
    {
        id: "aicte_2",
        type: "internship",
        title: "Data Science Intern",
        company: "MINDSEEKERS TECHNOLOGIES PRIVATE LIMITED",
        source: "AICTE",
        location: "Bangalore",
        amount: 10000,
        applyBy: "2025-12-05",
        skills: "Python, Pandas, Scikit-learn, SQL",
        url: "https://internship.aicte-india.org/internship-details.php?uid=SU5URVJOU0hJUF8xNzYyMDAxNTA3NjkwNjAyNjMxZjE1MQ=="
    },
    {
        id: "aicte_3",
        type: "internship",
        title: "FULL STACK DEVELOPER (JAVA)",
        company: "pixelwind technologies",
        source: "AICTE",
        location: "Visakapatanam",
        amount: 10000,
        applyBy: "2025-11-25",
        skills: "Market Research, JIRA, Product Roadmapping",
        url: "https://internship.aicte-india.org/internship-details.php?uid=SU5URVJOU0hJUF8xNzYyMDAwMTU0NjkwNWZkMWE3MmRhNg=="
    },
    {
        id: "aicte_4",
        type: "internship",
        title: "ARTIFICIAL INTELLIGENCE",
        company: "MINDSEEKERS TECHNOLOGIES PRIVATE LIMITED",
        source: "AICTE",
        location: "Virtual",
        amount: 8000,
        applyBy: "2025-12-10",
        skills: "Figma, Adobe XD, User Research",
        url: "https://internship.aicte-india.org/internship-details.php?uid=SU5URVJOU0hJUF8xNzYxOTk2ODQ4NjkwNWYwMzA5ZGY3Ng=="
    },
    {
        id: "aicte_5",
        type: "internship",
        title: "PYTHON AI AND PROMPT ENGINEERING INTERNSHIP",
        company: "VaultofCodes",
        source: "AICTE",
        location: "Hyderabad",
        amount: 18000,
        applyBy: "2025-12-15",
        skills: "AWS, Docker, Kubernetes, Terraform",
        url: "https://internship.aicte-india.org/internship-details.php?uid=SU5URVJOU0hJUF8xNzYxOTg2MzIxNjkwNWM3MTFiYjJkMw=="
    },
    {
        id: "aicte_6",
        type: "internship",
        title: "PYTHON - AI - ML - DATA SCIENCE - JAVA - WEBSITE DEVELOPMENT",
        company: "ROBOKWIK.COM",
        source: "AICTE",
        location: "New Delhi",
        amount: 5000,
        applyBy: "2025-11-28",
        skills: "SEO, SEM, Social Media, Content Writing",
        url: "https://internship.aicte-india.org/internship-details.php?uid=SU5URVJOU0hJUF8xNzYxOTc4Njg3NjkwNWE5M2YwZDRkYw=="
    },
    {
        id: "aicte_7",
        type: "internship",
        title: "SOFTWARE TESTING INTERN",
        company: "BluePlanet Infosolutions India Pvt Ltd",
        source: "AICTE",
        location: "Bangalore",
        amount: 16000,
        applyBy: "2025-12-08",
        skills: "Python, Django, REST APIs, PostgreSQL",
        url: "https://internship.aicte-india.org/internship-details.php?uid=SU5URVJOU0hJUF8xNzYxOTcwNzM3NjkwNThhMzFkN2YzOQ=="
    },
    {
        id: "aicte_8",
        type: "internship",
        title: "SCRIPT WRITER INTERN",
        company: "BluePlanet Infosolutions India Pvt Ltd",
        source: "AICTE",
        location: "Bangalore",
        amount: 1000,
        applyBy: "2025-12-08",
        skills: "Python, Django, REST APIs, PostgreSQL",
        url: "https://internship.aicte-india.org/internship-details.php?uid=SU5URVJOU0hJUF8xNzYxOTY3NzIxNjkwNTdlNjkxMDc1YQ=="
    },
    {
        id: "aicte_9",
        type: "internship",
        title: "PYTHON PROGRAMMING INTERNSHIP",
        company: "MAINCRAFTS COM",
        source: "AICTE",
        location: "Bangalore",
        amount: 10000,
        applyBy: "2025-12-08",
        skills: "Python, Django, REST APIs, PostgreSQL",
        url: "https://internship.aicte-india.org/internship-details.php?uid=SU5URVJOU0hJUF8xNzYxOTU5MjI2NjkwNTVkM2E1NWIyMA=="
    },
    {
        id: "aicte_10",
        type: "internship",
        title: "PHP DEVELOPER INTERN",
        company: "BluePlanet Infosolutions India Pvt Ltd",
        source: "AICTE",
        location: "Bangalore",
        amount: 0,
        applyBy: "2025-12-08",
        skills: "Python, Django, REST APIs, PostgreSQL",
        url: "https://internship.aicte-india.org/internship-details.php?uid=SU5URVJOU0hJUF8xNzYxOTI2ODg3NjkwNGRlZTc4YzVhMA=="
    },
    {
        id: "aicte_11",
        type: "internship",
        title: "WEB DEVELOMENT, JAVA FULL STACK AND PHP INTERNSHIP",
        company: "Soft Nexis Technology",
        source: "AICTE",
        location: "Bangalore",

        amount: 17000,
        applyBy: "2025-12-08",
        skills: "Python, Django, REST APIs, PostgreSQL",
        url: "hhttps://internship.aicte-india.org/internship-details.php?uid=SU5URVJOU0hJUF8xNzYxOTI2NTA4NjkwNGRkNmM1YmZlNA=="
    },
    {
        id: "aicte_12",
        type: "internship",
        title: "DEVOPS INTERN",
        company: "BluePlanet Infosolutions India Pvt Ltd",
        source: "AICTE",
        location: "Bangalore",
        amount: 10000,
        applyBy: "2025-12-08",
        skills: "Python, Django, REST APIs, PostgreSQL",
        url: "https://internship.aicte-india.org/recentlyposted.php"
    },
    {
        "id": "aicte_13",
        "type": "internship",
        "title": "WEB DEV / PYTHON / JAVA / AI AND PROMPT ENGINEERING INTERNSHIP",
        "company": "VaultofCodes",
        "source": "AICTE",
        "location": "Pan India",
        "amount": 0,
        "applyBy": "2025-11-05",
        "skills": null,
        "url": null
    },
    {
        id: "aicte_7",
        type: "internship",
        title: "Content and Social Media Marketing - Internship",
        company: "Mint global solutions",
        source: "Internshala",
        location: "Bangalore",
        amount: 16000,
        applyBy: "2025-12-08",
        skills: "Python, Django, REST APIs, PostgreSQL",
        url: "https://internshala.com/internship/detail/content-and-social-media-marketing-internship-in-multiple-locations-at-mint-global1761801202"
    },
    {
        id: "aicte_7",
        type: "internship",
        title: "Graphic Design - Internship",
        company: "Voyse Digital",
        source: "Internshala",
        location: "Bangalore",
        amount: 16000,
        applyBy: "2025-12-08",
        skills: "Python, Django, REST APIs, PostgreSQL",
        url: "https://internshala.com/internship/detail/graphic-design-internship-in-bangalore-at-voyse-digital1761828109"
    },
    {
        id: "aicte_7",
        type: "internship",
        title: "Project Management - Internship",
        company: "FunTune Solutions",
        source: "Internshala",
        location: "Bangalore",
        amount: 16000,
        applyBy: "2025-12-08",
        skills: "Python, Django, REST APIs, PostgreSQL",
        url: "https://internshala.com/internship/detail/project-management-internship-in-noida-at-fyntune-solution-private-limited1761894632"
    },
    {
        id: "aicte_7",
        type: "internship",
        title: "Social Media Marketing - Internship",
        company: "Expertbells Consulting Private Limited",
        source: "Internshala",
        location: "Bangalore",
        amount: 16000,
        applyBy: "2025-12-08",
        skills: "Python, Django, REST APIs, PostgreSQL",
        url: "https://internshala.com/internship/detail/social-media-marketing-internship-in-agra-at-expertbells-consulting-private-limited1761759207"
    },
    {
        "id": "internshala_1",
        "type": "internship",
        "title": "Swaraj Fellowship & Social Entrepreneurship",
        "company": "Hamari Pahchan NGO",
        "source": "Internshala",
        "location": "Work from home",
        "amount": 0,
        "applyBy": null,
        "skills": "MS-Office, Content Marketing, 3 weeks ago",
        "url":"https://internshala.com/internship/detail/work-from-home-part-time-swaraj-fellowship-social-entrepreneurship-internship-at-hamari-pahchan-ngo1759826370"
    },
    {
        "id": "internshala_2",
        "type": "internship",
        "title": "Reddit Marketing Executive",
        "company": "Digi Acai",
        "source": "Internshala",
        "location": "Work from home",
        "amount": 5000,
        "applyBy": null,
        "skills": "Community Management, 4 days ago",
        "url": "https://internshala.com/internship/detail/work-from-home-reddit-marketing-executive-internship-at-digi-acai1761659918"
    },
    {
        "id": "internshala_3",
        "type": "internship",
        "title": "Video Editing/Making",
        "company": "Wellness Garden",
        "source": "Internshala",
        "location": "Bangalore",
        "amount": 12000,
        "applyBy": null,
        "skills": "Adobe Photoshop, Adobe Illustrator, Video Editing, Adobe Premiere Pro, Final Cut Pro, Video Making, 1 week ago",
        "url": "https://internshala.com/internship/detail/work-from-home-part-time-video-editing-making-internship-at-wellness-garden1761210376"
    },
    {
        "id": "internshala_4",
        "type": "internship",
        "title": "Marketing",
        "company": "Tiny Twigs International Preschool",
        "source": "Internshala",
        "location": "Bangalore",
        "amount": 5000,
        "applyBy": null,
        "skills": "Social Media Marketing, Digital Marketing, English Proficiency (Spoken), 5 days ago",
        "url": "https://internshala.com/internship/detail/part-time-marketing-internship-in-bangalore-at-tiny-twigs-international-preschool1761541789"
    },
    {
        "id": "internshala_5",
        "type": "internship",
        "title": "AI Video & Avatar Creator (Visual Designer)",
        "company": "Aspirant AI",
        "source": "Internshala",
        "location": "Work from home",
        "amount": 3000,
        "applyBy": null,
        "skills": "Video Editing, Creative Thinking, Visual Basic (VB), Video Making, Image Editing, Visual Design, 1 week ago, Quality Assurance/Quality Control (QA/QC)",
        "url": "https://internshala.com/internship/detail/work-from-home-ai-video-avatar-creator-visual-designer-internship-at-aspirantai1761281671"
    },
    {
        "id": "internshala_6",
        "type": "internship",
        "title": "Content and Social Media Marketing",
        "company": "Hunt Digital Media",
        "source": "Internshala",
        "location": "Work from home",
        "amount": 4000,
        "applyBy": null,
        "skills": "Content Writing, Script Writing, Copywriting",
        "url": "https://internshala.com/internship/detail/work-from-home-content-and-social-media-marketing-internship-at-hunt-digital-media1762005303"
    },
    {
        "id": "internshala_7",
        "type": "internship",
        "title": "Digital Marketing",
        "company": "Crux Game Studios",
        "source": "Internshala",
        "location": "Work from home",
        "amount": 9000,
        "applyBy": null,
        "skills": "Social Media Marketing, Digital Marketing, Creative Writing, Email Marketing, English Proficiency (Spoken), English Proficiency (Written)",
        "url": "https://internshala.com/internship/detail/work-from-home-content-and-social-media-marketing-internship-at-hunt-digital-media1762005303"
    },
    {
        "id": "internshala_8",
        "type": "internship",
        "title": "Graphic Design",
        "company": "Brain Up Kids",
        "source": "Internshala",
        "location": "Work from home",
        "amount": 3000,
        "applyBy": null,
        "skills": "Adobe Photoshop, CorelDRAW, Adobe Illustrator, MS-PowerPoint, Adobe Premiere Pro, Adobe InDesign, Adobe After Effects",
        "url": "https://internshala.com/internship/detail/work-from-home-content-and-social-media-marketing-internship-at-hunt-digital-media1762005303"
    },
    {
        "id": "internshala_9",
        "type": "internship",
        "title": "Media & Public Relations (PR)",
        "company": "Creatorshala",
        "source": "Internshala",
        "location": "Work from home",
        "amount": 5000,
        "applyBy": null,
        "skills": "Social Media Marketing, Creative Writing, MS-Excel, English Proficiency (Spoken), English Proficiency (Written)",
        "url": "https://internshala.com/internship/detail/work-from-home-content-and-social-media-marketing-internship-at-hunt-digital-media1762005303"
    },
    {
        "id": "internshala_10",
        "type": "internship",
        "title": "Social Media Marketing",
        "company": "Creatorshala",
        "source": "Internshala",
        "location": "Work from home",
        "amount": 5000,
        "applyBy": null,
        "skills": "Social Media Marketing, Search Engine Marketing (SEM), Search Engine Optimization (SEO), Facebook Marketing, Email Marketing, English Proficiency (Written), Instagram Marketing",
        "url": "https://internshala.com/internship/detail/work-from-home-content-and-social-media-marketing-internship-at-hunt-digital-media1762005303"
    },
    {
        "id": "internshala_11",
        "type": "internship",
        "title": "Business Development (Sales)",
        "company": "The Oraiyan Groups",
        "source": "Internshala",
        "location": "Bangalore",
        "amount": 20000,
        "applyBy": null,
        "skills": "Social Media Marketing, Digital Marketing, Kannada Proficiency (Spoken), Effective Communication",
        "url": "https://internshala.com/internship/detail/work-from-home-content-and-social-media-marketing-internship-at-hunt-digital-media1762005303"
    },
    {
        "id": "internshala_12",
        "type": "internship",
        "title": "Lead Generation",
        "company": "Xchieve Edtech Private Limited",
        "source": "Internshala",
        "location": "Work from home",
        "amount": 4000,
        "applyBy": null,
        "skills": "Social Media Marketing, Leadership, Job offer upto ₹ 5LPA post internship, Email Marketing, Lead Generation, Effective Communication",
        "url": "https://internshala.com/internship/detail/work-from-home-content-and-social-media-marketing-internship-at-hunt-digital-media1762005303"
    },
    {
        "id": "internshala_13",
        "type": "internship",
        "title": "Student Marketing",
        "company": "Xchieve Edtech Private Limited",
        "source": "Internshala",
        "location": "Work from home",
        "amount": 3000,
        "applyBy": null,
        "skills": "Leadership, Email Marketing, Job offer upto ₹ 5LPA post internship, Lead Generation, English Proficiency (Spoken)",
        "url": "https://internshala.com/internship/detail/work-from-home-content-and-social-media-marketing-internship-at-hunt-digital-media1762005303"
    },
    {
        "id": "internshala_14",
        "type": "internship",
        "title": "Representative (Marketing)",
        "company": "Xchieve Edtech Private Limited",
        "source": "Internshala",
        "location": "Work from home",
        "amount": 3000,
        "applyBy": null,
        "skills": "Email Marketing, Lead Generation, Job offer upto ₹ 5LPA post internship, English Proficiency (Spoken), Effective Communication",
        "url": "https://internshala.com/internship/detail/work-from-home-content-and-social-media-marketing-internship-at-hunt-digital-media1762005303"
    },
    {
        "id": "internshala_15",
        "type": "internship",
        "title": "Motion Graphics",
        "company": "Across The Globe (ATG)",
        "source": "Internshala",
        "location": "Work from home",
        "amount": 8000,
        "applyBy": null,
        "skills": "Video Editing, Adobe Premiere Pro, Video Making, Animation, Adobe After Effects",
        "url": "https://internshala.com/internship/detail/work-from-home-content-and-social-media-marketing-internship-at-hunt-digital-media1762005303"
    },
    {
        "id": "internshala_16",
        "type": "internship",
        "title": "Social Media Design",
        "company": "Jarurat Care",
        "source": "Internshala",
        "location": "Work from home",
        "amount": 0,
        "applyBy": null,
        "skills": "Creativity, UI & UX Design, Coordination, Canva, Effective Communication",
        "url": "https://internshala.com/internship/detail/work-from-home-content-and-social-media-marketing-internship-at-hunt-digital-media1762005303"
    },
    {
        "id": "internshala_17",
        "type": "internship",
        "title": "Marketing & Social Media",
        "company": "Scene ON",
        "source": "Internshala",
        "location": "Bangalore",
        "amount": 5000,
        "applyBy": null,
        "skills": "Social Media Marketing, Creative Thinking, Content Marketing, Research and Analytics, Facebook Ads, Community Management",
        "url": "https://internshala.com/internship/detail/work-from-home-content-and-social-media-marketing-internship-at-hunt-digital-media1762005303"
    },
    {
        "id": "internshala_18",
        "type": "internship",
        "title": "Lead Generation",
        "company": "Tripple One Solutions",
        "source": "Internshala",
        "location": "Work from home",
        "amount": 3000,
        "applyBy": null,
        "skills": "Social Media Marketing, Digital Marketing, Job offer upto ₹ 4LPA post internship, Email Marketing, English Proficiency (Spoken), English Proficiency (Written)",
        "url": "https://internshala.com/internship/detail/work-from-home-content-and-social-media-marketing-internship-at-hunt-digital-media1762005303"
    },
    {
        "id": "internshala_19",
        "type": "internship",
        "title": "Visual Design",
        "company": "InAmigos Foundation",
        "source": "Internshala",
        "location": "Work from home",
        "amount": 2500,
        "applyBy": null,
        "skills": "English Proficiency (Spoken)",
        "url":"https://internshala.com/internship/detail/work-from-home-content-and-social-media-marketing-internship-at-hunt-digital-media1762005303"
    },
    {
        "id": "internshala_20",
        "type": "internship",
        "title": "Video Editing/Making",
        "company": "The Skill Guru Foundation",
        "source": "Internshala",
        "location": "Work from home",
        "amount": 0,
        "applyBy": null,
        "skills": "Video Editing",
        "url": "https://internshala.com/internship/detail/work-from-home-content-and-social-media-marketing-internship-at-hunt-digital-media1762005303"
    },
    {
        "id": "internshala_21",
        "type": "internship",
        "title": "Website & Social Media Content Creation",
        "company": "Aambr Innovise Private Limited",
        "source": "Internshala",
        "location": "Work from home",
        "amount": 10000,
        "applyBy": null,
        "skills": "Social Media Marketing, Content Writing, Copywriting, Content Management, English Proficiency (Written), Effective Communication, Pharmacology",
        "url": "https://internshala.com/internship/detail/work-from-home-content-and-social-media-marketing-internship-at-hunt-digital-media1762005303"
    },
    {
        "id": "internshala_22",
        "type": "internship",
        "title": "Video Editing and Graphic Designing",
        "company": "Avrithi Foodworks",
        "source": "Internshala",
        "location": "Work from home",
        "amount": 5000,
        "applyBy": null,
        "skills": "Adobe Photoshop, Adobe Illustrator, Job offer upto ₹ 3LPA post internship, Video Editing, Adobe Premiere Pro, Final Cut Pro, Canva, Filmora",
        "url": "https://internshala.com/internship/detail/work-from-home-content-and-social-media-marketing-internship-at-hunt-digital-media1762005303"
    },
    {
        "id": "internshala_23",
        "type": "internship",
        "title": "Social Media Video Content Editor",
        "company": "Intesome",
        "source": "Internshala",
        "location": "Work from home",
        "amount": 10000,
        "applyBy": null,
        "skills": "Adobe Illustrator, Video Editing, Adobe Premiere Pro, Final Cut Pro, Adobe Creative Suite, Adobe After Effects, Cinema 4D",
        "url": "https://internshala.com/internship/detail/work-from-home-content-and-social-media-marketing-internship-at-hunt-digital-media1762005303"
    },
    {
        "id": "internshala_24",
        "type": "internship",
        "title": "Video Editing/Making",
        "company": "Hunt Digital Media",
        "source": "Internshala",
        "location": "Work from home",
        "amount": 2000,
        "applyBy": null,
        "skills": "Adobe Photoshop, Video Editing, Video Making, 5 days ago",
        "url": "https://internshala.com/internship/detail/work-from-home-content-and-social-media-marketing-internship-at-hunt-digital-media1762005303"
    },
    {
        "id": "internshala_25",
        "type": "internship",
        "title": "Data Annotator (Road Infrastructure Project)",
        "company": "Globik AI",
        "source": "Internshala",
        "location": "Work from home",
        "amount": 10000,
        "applyBy": null,
        "skills": "Attention to Detail, Time Management, Coordination, Computer Vision, Teamwork, Artificial intelligence, Interpersonal skills",
        "url": "https://internshala.com/internship/detail/work-from-home-content-and-social-media-marketing-internship-at-hunt-digital-media1762005303"
    },
    {
        "id": "internshala_26",
        "type": "internship",
        "title": "Social Media Marketing (Reddit)",
        "company": "Warewe Consultancy Private Limited",
        "source": "Internshala",
        "location": "Work from home",
        "amount": 4000,
        "applyBy": null,
        "skills": "Social Media Marketing, Search Engine Optimization (SEO), 3 days ago",
        "url": "https://internshala.com/internship/detail/work-from-home-content-and-social-media-marketing-internship-at-hunt-digital-media1762005303"
    },
    {
        "id": "internshala_27",
        "type":"internship",
        "title": "Product Marketing",
        "company": "Webmobi",
        "source": "Internshala",
        "location": "Work from home",
        "amount": 5000,
        "applyBy": null,
        "skills": "Social Media Marketing, Search Engine Marketing (SEM), Digital Marketing, Email Marketing, English Proficiency (Spoken), 3 days ago, English Proficiency (Written), Marketing",
        "url": "https://internshala.com/internship/detail/work-from-home-content-and-social-media-marketing-internship-at-hunt-digital-media1762005303"
    },
    {
        "id": "internshala_28",
        "type": "internship",
        "title": "Social Media Photoshoot & Videography",
        "company": "Hotkhana.com",
        "source": "Internshala",
        "location": "Bangalore",
        "amount": 10000,
        "applyBy": null,
        "skills": "Video Editing, Videography, Job offer upto ₹ 3LPA post internship, Photography, Video Making, 3 weeks ago",
        "url": "https://internshala.com/internship/detail/work-from-home-content-and-social-media-marketing-internship-at-hunt-digital-media1762005303"
    },
    {
        "id": "internshala_29",
        "type": "internship",
        "title": "Content Creator (Malayalam Speaking)",
        "company": "SciAstra Education Private Limited",
        "source": "Internshala",
        "location": "Work from home",
        "amount": 4000,
        "applyBy": null,
        "skills": "Malayalam Proficiency (Spoken), Interpersonal skills, Effective Communication",
        "url": "https://internshala.com/internship/detail/work-from-home-content-and-social-media-marketing-internship-at-hunt-digital-media1762005303"
    },
    {
        "id": "internshala_30",
        "type": "internship",
        "title": "Content & Community Outreach",
        "company": "Navig (Ekam) Health",
        "source": "Internshala",
        "location": "Work from home",
        "amount": 3000,
        "applyBy": null,
        "skills": "Social Media Marketing",
        "url": "https://internshala.com/internship/detail/work-from-home-content-and-social-media-marketing-internship-at-hunt-digital-media1762005303"
    },
    {
        "id": "internshala_31",
        "type": "internship",
        "title": "Graphics Designing And Video Editing",
        "company": "Hotkhana.com",
        "source": "Internshala",
        "location": "Bangalore",
        "amount": 7000,
        "applyBy": null,
        "skills": "Adobe Photoshop, Adobe Illustrator, Job offer upto ₹ 2.4LPA post internship, Adobe Premiere Pro, Adobe After Effects, English Proficiency (Written), Capcut, 3 weeks ago",
        "url": "https://internshala.com/internship/detail/work-from-home-content-and-social-media-marketing-internship-at-hunt-digital-media1762005303"
    },
    {
        "id": "internshala_32",
        "type": "internship",
        "title": "Business Development & Client Servicing",
        "company": "Neugenic Mediventure Collective Private Limited",
        "source": "Internshala",
        "location": "Work from home",
        "amount": 6500,
        "applyBy": null,
        "skills": "Social Media Marketing, MS-Office, Job offer starting ₹ 2LPA post internship, Client Interaction, Operations, MS-Excel, Client Relationship Management (CRM), Marketing Strategy",
        "url": "https://internshala.com/internship/detail/work-from-home-content-and-social-media-marketing-internship-at-hunt-digital-media1762005303"
    },
    {
        "id": "internshala_33",
        "type": "internship",
        "title": "Community Influencing",
        "company": "Basti Ki Pathshala Foundation",
        "source": "Internshala",
        "location": "Work from home",
        "amount": 1500,
        "applyBy": null,
        "skills": "Effective Communication",
        "url": "https://internshala.com/internship/detail/work-from-home-content-and-social-media-marketing-internship-at-hunt-digital-media1762005303"
    },
    {
        "id": "internshala_34",
        "type": "internship",
        "title": "Motion Graphics and Video Editing/Making",
        "company": "Renan Partners",
        "source": "Internshala",
        "location": "Work from home",
        "amount": 5000,
        "applyBy": null,
        "skills": "Adobe Photoshop, Adobe Illustrator, Job offer upto ₹ 7LPA post internship, Video Editing, Adobe Premiere Pro, Final Cut Pro, 3 days ago, Video Making",
        "url": "https://internshala.com/internship/detail/work-from-home-content-and-social-media-marketing-internship-at-hunt-digital-media1762005303"
    },
    {
        "id": "internshala_35",
        "type": "internship",
        "title": "Python Development",
        "company": "Amrata",
        "source": "Internshala",
        "location": "Work from home",
        "amount": 12500,
        "applyBy": null,
        "skills": "HTML, CSS, Python, Django, Machine Learning, REST API, Flask",
        "url": "https://internshala.com/internship/detail/work-from-home-content-and-social-media-marketing-internship-at-hunt-digital-media1762005303"
    },
    {
        "id": "internshala_36",
        "type": "internship",
        "title": "Java Development",
        "company": "Amrata",
        "source": "Internshala",
        "location": "Work from home",
        "amount": 10000,
        "applyBy": null,
        "skills": "Java, MySQL, JSP, J2EE, Hibernate ORM(Java), Spring MVC",
        "url": "https://internshala.com/internship/detail/work-from-home-content-and-social-media-marketing-internship-at-hunt-digital-media1762005303"
    },
    {
        "id": "internshala_37",
        "type": "internship",
        "title": "Python Development",
        "company": "Scrymz Software Private Limited",
        "source": "Internshala",
        "location": "Work from home",
        "amount": 1000,
        "applyBy": null,
        "skills": "Python, FastAPI, APIs, NumPy, Pandas, Matplotlib",
        "url": "https://internshala.com/internship/detail/work-from-home-content-and-social-media-marketing-internship-at-hunt-digital-media1762005303"
    },
    {
        "id": "internshala_38",
        "type": "internship",
        "title": "Software Development Engineering (Web)",
        "company": "Brokod IT Consulting And Digital Marketing Solution",
        "source": "Internshala",
        "location": "Work from home",
        "amount": 3000,
        "applyBy": null,
        "skills": "MySQL, HTML, Job offer upto ₹ 4LPA post internship, CSS, JavaScript, MongoDB, Git, Node.js",
        "url": "https://internshala.com/internship/detail/work-from-home-content-and-social-media-marketing-internship-at-hunt-digital-media1762005303"
    },
    {
        "id": "internshala_39",
        "type": "internship",
        "title": "2d Illustrator",
        "company": "Contents Shark",
        "source": "Internshala",
        "location": "Work from home",
        "amount": 10000,
        "applyBy": null,
        "skills": "Adobe Illustrator, Digital Illustration",
        "url": "https://internshala.com/internship/detail/work-from-home-content-and-social-media-marketing-internship-at-hunt-digital-media1762005303"
    },
    {
        "id": "internshala_40",
        "type": "internship",
        "title": "Video Editing/Making",
        "company": "GemSeason",
        "source": "Internshala",
        "location": "Work from home",
        "amount": 1500,
        "applyBy": null,
        "skills": "Video Editing, Adobe Premiere Pro",
        "url": "https://internshala.com/internship/detail/work-from-home-content-and-social-media-marketing-internship-at-hunt-digital-media1762005303"
    },
    {
        "id": "internshala_41",
        "type": "internship",
        "title": "Shorts Video Editor",
        "company": "Feardog Music",
        "source": "Internshala",
        "location": "Work from home",
        "amount": 8000,
        "applyBy": null,
        "skills": "Adobe Photoshop, Adobe Premiere Pro, Adobe After Effects",
        "url": "https://internshala.com/internship/detail/work-from-home-content-and-social-media-marketing-internship-at-hunt-digital-media1762005303"
    },
    {
        "id": "internshala_42",
        "type": "internship",
        "title": "Shorts Writer",
        "company": "Feardog Music",
        "source": "Internshala",
        "location": "Work from home",
        "amount": 8000,
        "applyBy": null,
        "skills": "Content Writing, Creative Writing",
        "url": "https://internshala.com/internship/detail/work-from-home-content-and-social-media-marketing-internship-at-hunt-digital-media1762005303"
    },
    {
        "id": "internshala_43",
        "type": "internship",
        "title": "Bodycam Research And Writing",
        "company": "Feardog Music",
        "source": "Internshala",
        "location": "Work from home",
        "amount": 10000,
        "applyBy": null,
        "skills": "Research and Analytics",
        "url": "https://internshala.com/internship/detail/work-from-home-content-and-social-media-marketing-internship-at-hunt-digital-media1762005303"
    },
    {
        "id": "internshala_44",
        "type": "internship",
        "title": "Video Essay Writing",
        "company": "Feardog Music",
        "source": "Internshala",
        "location": "Work from home",
        "amount": 10000,
        "applyBy": null,
        "skills": "Creative Writing",
        "url": "https://internshala.com/internship/detail/work-from-home-content-and-social-media-marketing-internship-at-hunt-digital-media1762005303"
    },
    {
        "id": "internshala_45",
        "type": "internship",
        "title": "Tech And EV Script Writing",
        "company": "Feardog Music",
        "source": "Internshala",
        "location": "Work from home",
        "amount": 8000,
        "applyBy": null,
        "skills": "Content Writing, Creative Writing",
        "url": "https://internshala.com/internship/detail/work-from-home-content-and-social-media-marketing-internship-at-hunt-digital-media1762005303"
    },
    {
        "id": "internshala_46",
        "type": "internship",
        "title": "Space Writing",
        "company": "Feardog Music",
        "source": "Internshala",
        "location": "Work from home",
        "amount": 10000,
        "applyBy": null,
        "skills": "Content Writing, Creative Writing",
        "url": "https://internshala.com/internship/detail/work-from-home-content-and-social-media-marketing-internship-at-hunt-digital-media1762005303"
    },
    {
        "id": "internshala_47",
        "type": "internship",
        "title": "Content Ideation & Thumbnail Strategist",
        "company": "Feardog Music",
        "source": "Internshala",
        "location": "Work from home",
        "amount": 8000,
        "applyBy": null,
        "skills": "Adobe Photoshop, Adobe Illustrator, Poster Design",
        "url": "https://internshala.com/internship/detail/work-from-home-content-and-social-media-marketing-internship-at-hunt-digital-media1762005303"
    },
    {
        "id": "internshala_48",
        "type": "internship",
        "title": "Data Entry",
        "company": "Creatorshala",
        "source": "Internshala",
        "location": "Work from home",
        "amount": 3000,
        "applyBy": null,
        "skills": "MS-Office, MS-Excel",
        "url": "https://internshala.com/internship/detail/work-from-home-content-and-social-media-marketing-internship-at-hunt-digital-media1762005303"
    },
    {
        "id": "internshala_49",
        "type": "internship",
        "title": "Journalism",
        "company": "University Times",
        "source": "Internshala",
        "location": "Work from home",
        "amount": 3000,
        "applyBy": null,
        "skills": "English Proficiency (Written)",
        "url": "https://internshala.com/internship/detail/work-from-home-content-and-social-media-marketing-internship-at-hunt-digital-media1762005303"
    },
    {
        "id": "internshala_50",
        "type": "internship",
        "title": "Social Media Marketing",
        "company": "Clickniti Digital",
        "source": "Internshala",
        "location": "Work from home",
        "amount": 2000,
        "applyBy": null,
        "skills": "Social Media Marketing, Digital Marketing, Creative Writing, Instagram Marketing, Graphic Design",
        "url": "https://internshala.com/internship/detail/work-from-home-content-and-social-media-marketing-internship-at-hunt-digital-media1762005303"
    }
];
